version: '3.8'

services:
  ducky-blazor:
    build:
      context: .
      dockerfile: src/demo/Demo.BlazorWasm/Dockerfile
    container_name: ducky-blazor-app
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    restart: unless-stopped
    networks:
      - ducky-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health.json"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add Redis for distributed caching/state
  redis:
    image: redis:alpine
    container_name: ducky-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - ducky-network
    restart: unless-stopped

networks:
  ducky-network:
    driver: bridge

volumes:
  redis-data: