// Copyright (c) 2020-2026 Atypical Consulting SRL. All rights reserved.
// Atypical Consulting SRL licenses this file to you under the Apache-2.0 license.
// See the LICENSE file in the project root for full license information.

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Ducky.Generator.Tests;

public class ReducerSourceGeneratorTests
{
    private const string DuckyReducerAttributeSource =
        """
        namespace Ducky
        {
            [System.AttributeUsage(System.AttributeTargets.Class)]
            public sealed class DuckyReducerAttribute : System.Attribute { }
        }
        """;

    private const string InitialStateAttributeSource =
        """
        namespace Ducky
        {
            [System.AttributeUsage(System.AttributeTargets.Field | System.AttributeTargets.Property)]
            public sealed class InitialStateAttribute : System.Attribute { }
        }
        """;

    private const string CounterStateSource =
        """
        namespace Demo.AppStore;

        public record CounterState(int Count = 0);
        public record Increment(int Amount = 1);
        public record Reset;
        """;

    private const string CounterReducersSource =
        """
        namespace Demo.AppStore;

        [Ducky.DuckyReducer]
        public static partial class CounterReducers
        {
            public static CounterState On(CounterState state, Increment action)
                => state with { Count = state.Count + action.Amount };

            public static CounterState On(CounterState state, Reset _)
                => new CounterState();
        }
        """;

    private const string ExpectedCounterReducersSlice =
        """
        // <auto-generated />
        // This file is auto-generated by Ducky.

        namespace Demo.AppStore;

        public sealed class CounterReducersSlice : Ducky.SliceReducers<global::Demo.AppStore.CounterState>
        {
            public CounterReducersSlice()
            {
                On<global::Demo.AppStore.Increment>((state, action) => global::Demo.AppStore.CounterReducers.On(state, action));
                On<global::Demo.AppStore.Reset>((state, action) => global::Demo.AppStore.CounterReducers.On(state, action));
            }

            public override global::Demo.AppStore.CounterState GetInitialState()
            {
                return new global::Demo.AppStore.CounterState();
            }
        }

        """;

    private const string ReducerWithInitialStateSource =
        """
        namespace Demo.AppStore;

        [Ducky.DuckyReducer]
        public static partial class TodoReducers
        {
            [Ducky.InitialState]
            public static readonly TodoState Default = new TodoState("empty");

            public static TodoState On(TodoState state, AddTodo action)
                => state with { Name = action.Name };
        }

        public record TodoState(string Name);
        public record AddTodo(string Name);
        """;

    [Fact]
    public void GeneratesSliceReducerForCounterReducers()
    {
        // Arrange
        ReducerSourceGenerator generator = new();

        string[] sources = [DuckyReducerAttributeSource, CounterStateSource, CounterReducersSource];

        CSharpCompilation compilation = CSharpCompilation.Create(
            assemblyName: "TestAssembly",
            syntaxTrees: sources.Select(source => CSharpSyntaxTree.ParseText(source)),
            references: [MetadataReference.CreateFromFile(typeof(object).Assembly.Location)],
            options: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary)
        );

        // Act
        GeneratorDriver driver = CSharpGeneratorDriver.Create(generator);
        driver = driver.RunGenerators(compilation, TestContext.Current.CancellationToken);
        GeneratorDriverRunResult runResult = driver.GetRunResult();

        // Assert
        runResult.GeneratedTrees.ShouldNotBeEmpty();

        SyntaxTree generatedTree = runResult.GeneratedTrees
            .Single(tree => tree.FilePath.EndsWith("CounterReducersSlice.g.cs"));

        string generatedText = generatedTree
            .GetText(TestContext.Current.CancellationToken)
            .ToString()
            .Replace("\r\n", "\n");

        generatedText.ShouldBe(ExpectedCounterReducersSlice.Replace("\r\n", "\n"));
    }

    [Fact]
    public void GeneratesSliceReducerWithInitialStateMember()
    {
        // Arrange
        ReducerSourceGenerator generator = new();

        string[] sources = [DuckyReducerAttributeSource, InitialStateAttributeSource, ReducerWithInitialStateSource];

        CSharpCompilation compilation = CSharpCompilation.Create(
            assemblyName: "TestAssembly",
            syntaxTrees: sources.Select(source => CSharpSyntaxTree.ParseText(source)),
            references: [MetadataReference.CreateFromFile(typeof(object).Assembly.Location)],
            options: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary)
        );

        // Act
        GeneratorDriver driver = CSharpGeneratorDriver.Create(generator);
        driver = driver.RunGenerators(compilation, TestContext.Current.CancellationToken);
        GeneratorDriverRunResult runResult = driver.GetRunResult();

        // Assert
        runResult.GeneratedTrees.ShouldNotBeEmpty();

        SyntaxTree generatedTree = runResult.GeneratedTrees
            .Single(tree => tree.FilePath.EndsWith("TodoReducersSlice.g.cs"));

        string generatedText = generatedTree
            .GetText(TestContext.Current.CancellationToken)
            .ToString();

        // Verify it uses the custom initial state
        generatedText.ShouldContain("global::Demo.AppStore.TodoReducers.Default");
    }

    [Fact]
    public void DoesNotGenerateForNonDecoratedClass()
    {
        // Arrange
        ReducerSourceGenerator generator = new();

        var source =
            """
            namespace Demo.AppStore;

            public static partial class PlainClass
            {
                public static int On(int state, string action) => state;
            }
            """;

        CSharpCompilation compilation = CSharpCompilation.Create(
            assemblyName: "TestAssembly",
            syntaxTrees: [CSharpSyntaxTree.ParseText(source, cancellationToken: TestContext.Current.CancellationToken)],
            references: [MetadataReference.CreateFromFile(typeof(object).Assembly.Location)],
            options: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary)
        );

        // Act
        GeneratorDriver driver = CSharpGeneratorDriver.Create(generator);
        driver = driver.RunGenerators(compilation, TestContext.Current.CancellationToken);
        GeneratorDriverRunResult runResult = driver.GetRunResult();

        // Assert — no files should be generated
        runResult.GeneratedTrees.ShouldBeEmpty();
    }

    [Fact]
    public void ReportsDiagnosticForInconsistentStateTypes()
    {
        // Arrange
        ReducerSourceGenerator generator = new();

        string[] sources =
        [
            DuckyReducerAttributeSource,
            """
            namespace Demo.AppStore;

            public record StateA(int X);
            public record StateB(string Y);
            public record ActionA;
            public record ActionB;

            [Ducky.DuckyReducer]
            public static partial class BadReducers
            {
                public static StateA On(StateA state, ActionA action) => state;
                public static StateB On(StateB state, ActionB action) => state;
            }
            """
        ];

        CSharpCompilation compilation = CSharpCompilation.Create(
            assemblyName: "TestAssembly",
            syntaxTrees: sources.Select(source => CSharpSyntaxTree.ParseText(source)),
            references: [MetadataReference.CreateFromFile(typeof(object).Assembly.Location)],
            options: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary)
        );

        // Act
        GeneratorDriver driver = CSharpGeneratorDriver.Create(generator);
        driver = driver.RunGenerators(compilation, TestContext.Current.CancellationToken);
        GeneratorDriverRunResult runResult = driver.GetRunResult();

        // Assert — should have a DUCKY001 diagnostic
        runResult.Diagnostics
            .Where(d => d.Id == "DUCKY001")
            .ShouldNotBeEmpty();
    }
}
