using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Probe.Generator;

/// <summary>Emits <c>{Name}Greeter</c> for every partial class; skips non-partial ones.</summary>
[Generator(LanguageNames.CSharp)]
public sealed class GreeterGenerator : IIncrementalGenerator
{
    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var names = context.SyntaxProvider.CreateSyntaxProvider(
            static (node, _) => node is ClassDeclarationSyntax,
            static (ctx, _) => (ClassDeclarationSyntax)ctx.Node)
            .Where(static c => c.Modifiers.Any(m => m.ValueText == "partial"))
            .Select(static (c, _) => c.Identifier.ValueText);

        context.RegisterSourceOutput(names, static (spc, name) =>
            spc.AddSource($"{name}Greeter.g.cs", $"// <auto-generated/>\npublic static class {name}Greeter {{ public static string Hello() => \"{name}\"; }}\n"));
    }
}
